### ISSUE TITLE
Update configure to log out injected keys

### ISSUE THREAD

**Issue by mauleb** [JBKLabs/react-dev#34]
## Description

At the moment, `configure` succeeds silently, however, there is no indication whether or not certain config keys are being replaced or not.

## Implementation

* [ ] update `configure` to log out each key found and whether or not they were injected

**Comment by byhag** [comment]
I'm working on this one.

**Comment by mauleb** [comment]
Just go ahead and assign yourself. That way we can tell at a glance which issues are claimed.
